#! /usr/bin/perl -w
#
# Generate the fontinformation tables for the required fonts (Linux version)
#

@charnames1 = (
"ellipsis", "trademark", "perthousand", "bullet",
"quoteleft", "quoteright", "guilsinglleft", "guilsinglright",
"quotedblleft", "quotedblright", "quotedblbase", "endash", "emdash",
"minus", "OE", "oe", "dagger", "daggerdbl", "fi", "fl",
"space", "exclamdown", "cent", "sterling", "currency",
"yen", "brokenbar", "section", "dieresis", "copyright",
"ordfeminine", "guillemotleft", "logicalnot", "hyphen", "registered",
"macron", "degree", "plusminus", "twosuperior", "threesuperior",
"acute", "mu", "paragraph", "periodcentered", "cedilla",
"onesuperior", "ordmasculine", "guillemotright", "onequarter",
"onehalf", "threequarters", "questiondown", "Agrave", "Aacute",
"Acircumflex", "Atilde", "Adieresis", "Aring", "AE", "Ccedilla",
"Egrave", "Eacute", "Ecircumflex", "Edieresis", "Igrave", "Iacute",
"Icircumflex", "Idieresis", "Eth", "Ntilde", "Ograve", "Oacute",
"Ocircumflex", "Otilde", "Odieresis", "multiply", "Oslash",
"Ugrave", "Uacute", "Ucircumflex", "Udieresis", "Yacute", "Thorn",
"germandbls", "agrave", "aacute", "acircumflex", "atilde",
"adieresis", "aring", "ae", "ccedilla", "egrave", "eacute",
"ecircumflex", "edieresis", "igrave", "iacute", "icircumflex",
"idieresis", "eth", "ntilde", "ograve", "oacute", "ocircumflex",
"otilde", "odieresis", "divide", "oslash", "ugrave", "uacute",
"ucircumflex", "udieresis", "yacute", "thorn", "ydieresis"
);

@charnames2 = (
"space", "Aogonek", "breve", "Lslash", "currency", "Lcaron",
"Sacute", "section", "dieresis", "Scaron", "Scedilla",
"Tcaron", "Zacute", "hyphen", "Zcaron", "Zdotaccent", "ring",
"aogonek", "ogonek", "lslash", "acute", "lcaron", "sacute",
"caron", "cedilla", "scaron", "scedilla", "tcaron",
"zacute", "hungarumlaut", "zcaron", "zdotaccent", "Racute",
"Aacute", "Acircumflex", "Abreve", "Adieresis", "Lacute",
"Cacute", "Ccedilla", "Ccaron", "Eacute", "Eogonek",
"Edieresis", "Ecaron", "Iacute", "Icircumflex", "Dcaron",
"Dslash", "Nacute", "Ncaron", "Oacute", "Ocircumflex",
"Ohungarumlaut", "Odieresis", "multiply", "Rcaron", "Uring",
"Uacute", "Uhungarumlaut", "Udieresis", "Yacute", "Tcommaaccent",
"germandbls", "racute", "aacute", "acircumflex", "abreve",
"adieresis", "lacute", "cacute", "ccedilla", "ccaron", "eacute",
"eogonek", "edieresis", "ecaron", "iacute", "icircumflex",
"dcaron", "dmacron", "nacute", "ncaron", "oacute", "ocircumflex",
"ohungarumlaut", "odieresis", "divide", "rcaron", "uring",
"uacute", "uhungarumlaut", "udieresis", "yacute", "tcommaaccent",
"dotaccent"
);

$gs_dir1 = '/usr/share/ghostscript/fonts';
$gs_dir2 = '/usr/share/ghostscript/fonts2';

@fontnames = (
"Courier", "Courier-Bold", "Courier-Oblique", "Courier-BoldOblique",
"Times-Roman", "Times-Bold", "Times-Italic", "Times-BoldItalic",
"Helvetica", "Helvetica-Bold", "Helvetica-Oblique", "Helvetica-BoldOblique",
"Palatino-Roman", "Palatino-Bold", "Palatino-Italic", "Palatino-BoldItalic",
"Helvetica-Narrow", "Helvetica-Narrow-Bold", "Helvetica-Narrow-Oblique", "Helvetica-Narrow-BoldOblique",
"Bookman-Light", "Bookman-Demi", "Bookman-LightItalic", "Bookman-DemiItalic",
"AvantGarde-Book", "AvantGarde-Demi", "AvantGarde-BookOblique", "AvantGarde-DemiOblique",
"NewCenturySchlbk-Roman", "NewCenturySchlbk-Bold", "NewCenturySchlbk-Italic", "NewCenturySchlbk-BoldItalic",
);


# Generate the array with the fontnames
sub generate_fontnames
{
	printf STDOUT "static const char *szFontnames[%d] = {\n", $#fontnames + 1;
	for ($n = 0; $n <= $#fontnames; $n++) {
		printf STDOUT "\t\"%s\",\n", $fontnames[$n];
	}
	printf STDOUT "};\n";
}

# Generate the array with the underline information
sub generate_underline_information
{
	printf STDOUT "#if 0 /* Until this array is needed */\n";

	printf STDOUT "static int aiUnderlineInfo[%d][2] = {\n", $#fontnames + 1;
	for ($n = 0; $n <= $#fontnames; $n++) {
		if (!defined($underlineposition[$n])) {
			$underlineposition[$n] = 0;
		}
		if (!defined($underlinethickness[$n])) {
			$underlinethickness[$n] = 0;
		}
		printf STDOUT "\t{ %d, %d },\n", $underlineposition[$n], $underlinethickness[$n];
	}
	printf STDOUT "};\n";

	printf STDOUT "#endif /* 0 */\n";
}


# main()

if ($#charnames1 != 255 - 140) {
	die "The charname1 table length is $#charnames1";
}
if ($#charnames2 != 255 - 160) {
	die "The charname2 table length is $#charnames2";
}

printf STDOUT "/* THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT! */\n";

&generate_fontnames();
&generate_underline_information();

exit 0;
